{
 "title": "My Web API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   { "name": "endpoint", "label": "Endpoint", "query": { "query": "label_values(endpoint)" } },
   { "name": "client", "label": "client", "query": { "query": "label_values(client)" } },
   { "name": "externalservice", "label": "External Service", "query": { "query": "label_values(service)" } },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "error", "label": "Http Status", "query": { "query": "label_values(response_code)" } }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": " Request Count By Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance)(increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval]))  / ignoring (instance) group_left sum (increase(application_request_counter[$interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Request Count By Application",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (client)(increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) / ignoring (client) group_left sum (increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) * 100",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": " Request Count By Endpoint",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint)(increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) / ignoring (endpoint) group_left sum (increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) * 100",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": " Request Count By Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service)(increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) / ignoring (service) group_left sum (increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) * 100",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": " Request Count By HttpStatusCode",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (response_code)(increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) / ignoring (response_code) group_left sum (increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) * 100",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": " Request Percent in Mobile",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (client)(increase(application_request_counter{client!=\"API\",client!=\"Website\",endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) / ignoring (client) group_left sum (increase(application_request_counter{client!=\"API\",client!=\"Website\",endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) * 100",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Application Performance Index",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (increase(application_request_counter{response_code=\"200\"}[$interval])) / sum (increase(application_request_counter[$interval]))  * 100",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Request Average Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (client)  (increase(application_request_duration{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) / sum by (client) (increase(application_request_duration{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval]))",
     "legendFormat": "{{ application }}"
    }
   ]
  },
  {
   "title": "Endpoint Request Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint)(increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Endpoint Request Error Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(application_request_counter{endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\",response_code=~\"$error\"}[$interval]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum (increase(application_request_counter{endpoint!=\"\",response_code=\"200\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\",response_code=~\"$error\"}[$interval]))",
     "legendFormat": "Successful Requests "
    },
    {
     "expr": "sum (increase(application_request_counter{endpoint!=\"\",response_code!=\"200\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\",response_code=~\"$error\"}[1m]))",
     "legendFormat": "Not Successful Requests"
    }
   ]
  },
  {
   "title": "API",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (client) (increase(application_request_counter{client=\"API\",endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval])) - sum by (client) (increase(application_request_counter{client=\"API\",endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval] offset 1h))) / sum by (client) (increase(application_request_counter{client=\"API\",endpoint!=\"\",endpoint=~\"$endpoint\",client=~\"$client\",service=~\"$externalservice\"}[$interval] offset 1h)) * 100",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Android",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (application) (increase(application_request_counter{application=\"Android\",endpoint!=\"\",endpoint=~\"$endpoint\",application=~\"$application\",service=~\"$externalservice\"}[$interval])) - sum by (application) (increase(application_request_counter{application=\"Android\",endpoint!=\"\",endpoint=~\"$endpoint\",application=~\"$application\",service=~\"$externalservice\"}[$interval] offset 1h))) / sum by (application) (increase(application_request_counter{application=\"Android\",endpoint!=\"\",endpoint=~\"$endpoint\",application=~\"$application\",service=~\"$externalservice\"}[$interval] offset 1h)) * 100",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Website",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (application) (increase(application_request_counter{application=\"Website\",endpoint!=\"\",endpoint=~\"$endpoint\",application=~\"$application\",service=~\"$externalservice\"}[$interval])) - sum by (application) (increase(application_request_counter{application=\"Website\",endpoint!=\"\",endpoint=~\"$endpoint\",application=~\"$application\",service=~\"$externalservice\"}[$interval] offset 1h))) / sum by (application) (increase(application_request_counter{application=\"Website\",endpoint!=\"\",endpoint=~\"$endpoint\",application=~\"$application\",service=~\"$externalservice\"}[$interval] offset 1h)) * 100",
     "legendFormat": "{{application}}"
    }
   ]
  }
 ]
}